/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package worksheet2.view;

import worksheet2.model.Employee;
import worksheet2.model.Sucursal;

public class MainWindow extends javax.swing.JFrame {

   
    public MainWindow() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterEmployeeBtn = new javax.swing.JButton();
        enterSucursalBtn = new javax.swing.JButton();
        consoleBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enterEmployeeBtn.setText("Ingresar empleados");
        enterEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterEmployeeBtnActionPerformed(evt);
            }
        });

        enterSucursalBtn.setText("Ingresar sucursal");
        enterSucursalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterSucursalBtnActionPerformed(evt);
            }
        });

        consoleBtn.setText("Mostrar en consola");
        consoleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consoleBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enterEmployeeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enterSucursalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consoleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(enterEmployeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enterSucursalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(consoleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterEmployeeBtnActionPerformed
        this.dispose();
        EmployeeWindow employeeWindow = new EmployeeWindow();
        employeeWindow.setVisible(true);
    }//GEN-LAST:event_enterEmployeeBtnActionPerformed

    private void enterSucursalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterSucursalBtnActionPerformed
        this.dispose();
        SucursalWindow sucursalWindow = new SucursalWindow();
        sucursalWindow.setVisible(true);
    }//GEN-LAST:event_enterSucursalBtnActionPerformed

    private void consoleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consoleBtnActionPerformed
        CompanyWindow.currentCompany.setEmployeeList(EmployeeWindow.currentEmployeeList);
    }//GEN-LAST:event_consoleBtnActionPerformed

    private void printConsole(){
        System.out.println( "Nombre de la empresa: "+CompanyWindow.currentCompany.getName() +"\n"+
        "Direccion de la empresa: "+ CompanyWindow.currentCompany.getAddress() + "\n" +
            "Telefono de la empresa: "+ CompanyWindow.currentCompany.getPhone() +"\n" +
                "---------- EMPLEADOS ---------" + "\n");
        printEmployees();
        printSucursales();
        System.out.println("---------- SUCURSALES ----------");
        printSucursales();
    }
    
    private void printEmployees(){
        for(Employee employee: CompanyWindow.currentCompany.getEmployeeList()){
            if(employee!=null){
                System.out.println(employee.getName());
            }
        }
    }
    
    private void printSucursales(){
        for(Sucursal sucursal: SucursalWindow.sucursalList){
            if(sucursal!=null){
                System.out.println("Sucursal: " +sucursal.getName()+ "\n"+
                        "Direccion sucursal: " + sucursal.getAddress() + "\n" + 
                            " ---------- EMPLEADOS DE LA SUCURSAL ---------- "  +"\n");
                for(Employee employee: sucursal.getEmployeeList()){
                    if(employee!=null){
                        System.out.println(employee.getName());
                    }
                }
                System.out.println("-----------------------------------------------------------");
            }
        }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consoleBtn;
    private javax.swing.JButton enterEmployeeBtn;
    private javax.swing.JButton enterSucursalBtn;
    // End of variables declaration//GEN-END:variables
}
